
project_id = "nqugsmhlnunxioauianh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true
port = 5000

[functions.validate-display-name]
verify_jwt = false

[functions.add-user-to-beehiiv]
verify_jwt = false

[functions.check-answer]
verify_jwt = false

[functions.get-game-leaderboard]
verify_jwt = false

[functions.get-random-hl-player]
verify_jwt = false

[functions.get-user-game-score]
verify_jwt = false

[functions.submit-hl-score]
verify_jwt = false

[functions.suggest-player-correction]
verify_jwt = false
